codecov:
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default:
        target: 70%
        threshold: 1%
        paths:
          - "game/"
          - "solver/"
        
    patch:
      default:
        target: 80%
        threshold: 1%
        
    changes: no

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: no
  require_base: no
  require_head: yes

ignore:
  - "**/*_test.go"
  - "**/testutil/**"
  - "**/examples/**"
  - "**/vendor/**"
  - "main.go"
  - "tui/**"

flags:
  unittests:
    paths:
      - game/
      - solver/
    carryforward: true