linters:
  enable:
    - gofmt
    - govet
    - errcheck
    - ineffassign
    - unused
    - staticcheck
    - gosimple
    - goconst
    - goimports
    - misspell
    - unconvert
    - prealloc
    - nakedret

linters-settings:
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/r-horie/ai-minesweeper
  goconst:
    min-len: 3
    min-occurrences: 3
  nakedret:
    max-func-lines: 30

run:
  deadline: 5m
  tests: true

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - ineffassign